var timeout, xhr; function popUpAlert(a, b) { msg = a.replace("{0}", '<span style="color:Red;">' + $("#ddlAccTo").find("option:selected").text() + "</span>").replace("{0}", '<span style="color:Red;">' + $("#ddlAccTo").find("option:selected").text() + "</span>"); $("<div >" + msg + "</div>").dialog({ modal: !0, title: b, width: 400, buttons: { OK: function () { $(this).dialog("close") } } }) }
function updatePanel(a, b) { $("#tempBtnClicked").val(a); $("#tempYear").val(b); $("#btnReload").click(); $("html, body").animate({ scrollTop: 400 }, "slow"); var c = $(".history_nav").height(), g = $(".historyContent").height(), c = c + g + 20; $(".searchLoadingImg").css("display", "block"); $(".searchLoadingImg").css("height", c) }
function setDate() { var a = $("#ddlYear").val(), b = $("#ddlMonth").val(); if ("" != b && "" != a) var c = "1/" + b + "/" + a, a = Math.round((new Date(a, b) - new Date(a, b - 1)) / 864E5) + "/" + b + "/" + a; else { var g = new Date, a = g.getDate(), b = g.getMonth() + 1, k = g.getFullYear(); g.setDate(g.getDate() - 7); var c = g.getDate(), l = g.getMonth() + 1, g = g.getFullYear(), c = c + "/" + l + "/" + g, a = a + "/" + b + "/" + k } $("#lblPeriod").text(c + " - " + a) }
function clickReload() { timeout && clearTimeout(timeout); xhr && xhr.abort(); timeout = setTimeout(function () { $("#btnReload").click() }, 500) } function getHistoryLoading() { var a = $(".history_nav").height(), b = $(".historyContent").height(), a = a + b + 20; $(".searchLoadingImg").css("display", "block"); $(".searchLoadingImg").css("height", a) } function resetForm(a) { $("#MainForm").clearForm(); 1 != a && $(".error,.amountError,#divMsg").html("") }
function trimZero(a) { var b = $(a).val(); if (-1 == b.indexOf(".") && 1 < b.length) for (; "0" === b.substring(0, 1) ;) b = b.substring(1); else if (-1 != b.indexOf(".") && 2 < b.length) { for (; !/^\d+(\.{0,1}\d{0,2})?$/.test(b) ;) b = b.substring(0, b.length - 1); for (; "00" === b.substring(0, 2) ;) b = b.substring(1) } $(a).val(b) }
function checkDigit(a, b, c, g) { if (window.event) a = window.event.keyCode; else if (a) a = a.which; else return !0; b.value.split("."); return 46 == a || 8 == a || 9 == a || 27 == a || 13 == a || 190 == a || 65 == a && !0 === event.ctrlKey || 35 <= a && 39 >= a ? !0 : event.shiftKey || (48 > a || 57 < a) && (96 > a || 105 < a) ? (event.preventDefault(), !1) : !0 } function removeRougeChar(a) { return "," == a.substring(0, 1) ? a.substring(1, a.length) : a } function checkBBIN() { return "BOY2" == $("#ddlAccTo").val() || "BOY2" == $("#ddlAccFrom").val() }
function checkIPSB() { return "IPSB" == $("#ddlAccTo").val() || "IPSB" == $("#ddlAccFrom").val() } function checkAG() { return "AG" == $("#ddlAccTo").val() || "AG" == $("#ddlAccFrom").val() } function checkSP() { return "SP" == $("#ddlAccTo").val() || "SP" == $("#ddlAccFrom").val() } function checkAB() { return "AB" == $("#ddlAccTo").val() || "AB" == $("#ddlAccFrom").val() }
function convertWithComma(a) { a = $(a); var b = a.val().replace(/[^0-9\.]+/g, "").replace(/,/gi, "").split("").reverse().join(""), b = removeRougeChar(b.replace(/(([0-9]{2,}\.)?(\d{3}))/g, "$1,").split("").reverse().join("")); a.val(b) }
$(document).ready(function () {
    $("#txtAmount").on("focus", function (a) { a = $(this); var b = a.val().replace(/,/g, ""); a.val(b) }).on("blur", function (a) { a = $(this); var b = a.val().replace(/[^0-9\.]+/g, "").replace(/,/gi, "").split("").reverse().join(""), b = removeRougeChar(b.replace(/(([0-9]{2,}\.)?(\d{3}))/g, "$1,").split("").reverse().join("")); a.val(b) }); try { $.validator.addMethod("DigitRegex", function (a, b, c) { c = new RegExp(c); return this.optional(b) || c.test(a.replace(/,/g, "")) }, "") } catch (a) { console.log(a) } try {
        $.validator.addMethod("regex",
        function (a, b, c) { c = new RegExp(c); return this.optional(b) || c.test(a) }, "")
    } catch (a) { console.log(a) } try { $.validator.addMethod("boydigit", function (a, b, c) { c = /^\d+$/; return checkBBIN() ? this.optional(b) || c.test(a.replace(/,/g, "")) : !0 }, "") } catch (a) { console.log(a) } try { $.validator.addMethod("AGdecimal", function (a, b, c) { c = /^\d+(\.[0]{1,2})?$/; return "AG" == $("#ddlAccFrom").val() ? this.optional(b) || c.test(a.replace(/,/g, "")) : !0 }, "") } catch (a) { console.log(a) }
});
function alignSubMenuToLeft(a, b) { $(a + " li:first-child").css("margin-left", $(b).position().left) } function alignSubMenuToRight(a, b) { $(a + " li").css("float", "right"); $(a).children().each(function (b, g) { $(a).prepend(g) }); $(a + " li:first-child").css("margin-right", $(a).width() - calculateRightPosition($(b))) } function calculateRightPosition(a) { return $(a).position().left + $(a).width() + 15 }
function distributeMenuPadding(a) { var b = $(a).width(), c = 0, g = 0, k = 0, l = 0; $(a).children().each(function (a, b) { 0 == a || $(b).hasClass("menuSeperator") ? (k += $(b).width(), c++) : (l += $(b).children("a").width(), g++) }); var m = b - k - 10 * c; $(a).children().each(function (a, b) { if (0 < a && !$(b).hasClass("menuSeperator")) { var c = ($(b).children("a").width() + parseInt($(b).children("a").css("padding-left")) + 0) / (l + k); $(b).width(c * m) } else 0 < a && ($(b).css("padding-left", 5), $(b).css("padding-right", 5)) }); $(a).css("visibility", "visible") }
function popUpWindowManager(a, b, c) { var g = window.location.pathname.split("/"); "" == g[g.length - 1] && -1 != a.indexOf("..") && (a = a.split("..").join("")); window.open(a, b, "height=" + (screen.availHeight - 70) + ", width=" + c + ",resizable=yes,scrollbars=yes,toolbar=no,menubar=no,location=no,directories=no, status=yes,top=0") } function popUpColorBox(a) { $.colorbox({ top: 10, href: a, fixed: !0, onClosed: function () { $.colorbox.close() } }) }
function marqueeInit(a) { document.createElement && (marqueeInit.ar.push(a), marqueeInit.run(a.uniqueid)) }
(function () {
    function a(a) { for (var b = [], d = 0, e; (e = a.firstChild) && 3 === e.nodeType && m[0].test(e.nodeValue) ;) a.removeChild(e); for (; (e = a.lastChild) && 3 === e.nodeType && m[0].test(e.nodeValue) ;) a.removeChild(e); (e = a.firstChild) && 3 === e.nodeType && (e.nodeValue = e.nodeValue.replace(m[1], "")); for ((e = a.lastChild) && 3 === e.nodeType && (e.nodeValue = e.nodeValue.replace(m[2], "")) ; e = a.firstChild;) b[d++] = a.removeChild(e); return b } function b(a) {
        for (var b = a.getElementsByTagName("*"), d = b.length, e = []; -1 < --d;) b[d].parentNode === a &&
        e.push(b[d]); e.sort(function () { return .5 - Math.random() }); for (d = e.length; -1 < --d;) a.appendChild(e[d])
    } function c(n, h) {
        var d, e, c, g, f, k, l = this; this.mq = marqueeInit.ar[n]; this.mq.random && (h.getElementsByTagName && 1 === h.getElementsByTagName("tr").length && 1 === h.childNodes.length ? b(h.getElementsByTagName("tr")[0]) : b(h)); for (d in p) if (this.mq.hasOwnProperty && !this.mq.hasOwnProperty(d) || !this.mq.hasOwnProperty && !this.mq[d]) this.mq[d] = p[d]; this.mq.direction = this.mq.persist && this.cookie.get(this.mq.uniqueid) ? this.cookie.get(this.mq.uniqueid).split(":")[2] :
        this.mq.direction; this.mq.style.width = !this.mq.style.width || isNaN(parseInt(this.mq.style.width)) ? "100%" : this.mq.style.width; h.getElementsByTagName("img")[0] ? this.mq.style.height = !this.mq.style.height || isNaN(parseInt(this.mq.style.height)) ? "auto" : this.mq.style.height : this.mq.style.height = !this.mq.style.height || isNaN(parseInt(this.mq.style.height)) ? h.offsetHeight + 3 + "px" : this.mq.style.height; e = this.mq.style.width.split(/\d/); this.cw = this.mq.style.width ? [parseInt(this.mq.style.width), e[e.length - 1]] : ["a"];
        k = a(h); h.className = h.id = ""; h.removeAttribute("class", 0); h.removeAttribute("id", 0); h.appendChild(h.cloneNode(!1)); h.className = ["marquee", n].join(""); h.style.overflow = "hidden"; this.c = h.firstChild; this.c.appendChild(this.c.cloneNode(!1)); this.c.style.visibility = "hidden"; e = [[r, this.c.style], [this.mq.style, this.c.style]]; for (f = e.length - 1; -1 < f; --f) for (d in e[f][0]) if (e[f][0].hasOwnProperty && e[f][0].hasOwnProperty(d) || !e[f][0].hasOwnProperty) e[f][1][d.encamel()] = e[f][0][d]; this.m = this.c.firstChild; "pause" ===
        this.mq.mouse && (this.c.onmouseover = function () { l.mq.stopped = !0 }, this.c.onmouseout = function () { l.mq.stopped = !1 }); this.m.style.position = "absolute"; this.m.style.left = "-100000px"; this.m.style.whiteSpace = "nowrap"; this.mq.noAddedSpace || this.m.appendChild(document.createTextNode("\u00a0")); for (f = 0; k[f]; ++f) this.m.appendChild(k[f]); c = this.m.getElementsByTagName("img"); if (c.length) for (f = g = 0; f < c.length; ++f) c[f].style.display = "inline", c[f].alt || this.mq.noAddedAlt || (c[f].alt = m[3].exec(c[f].src) || "Image #" + [f + 1],
        c[f].title || (c[f].title = "")), c[f].style.display = "inline", c[f].style.verticalAlign = c[f].style.verticalAlign || "top", "boolean" === typeof c[f].complete && c[f].complete ? g++ : c[f].onload = c[f].onerror = function () { ++g === c.length && l.setup(n) }, g === c.length && this.setup(n); else this.setup(n)
    } function g() {
        for (var a, b, d, c = 0; c < marqueeInit.ar.length; ++c) if (marqueeInit.ar[c] && marqueeInit.ar[c].setup) for (d = marqueeInit.ar[c].setup, a = d.mq.moveatleast ? Math.max(d.mq.moveatleast, d.sinc) : d.sinc || d.mq.inc, d.c.style.width = d.mq.style.width,
        d.cw[0] = 1 < d.cw.length ? parseInt(d.mq.style.width) : "a"; d.c.offsetWidth > d.w - a;) { b = isNaN(d.cw[0]) ? d.w - a : --d.cw[0]; if (1 > b) break; d.c.style.width = isNaN(d.cw[0]) ? d.w - a + "px" : --d.cw[0] + d.cw[1] }
    } function k() { for (var a, b = 0; b < marqueeInit.ar.length; ++b) marqueeInit.ar[b] && marqueeInit.ar[b].persist && marqueeInit.ar[b].setup && (a = marqueeInit.ar[b].setup, a.cookie.set(a.mq.uniqueid, a.m[0].style.left + ":" + a.m[1].style.left + ":" + a.mq.direction)) } if (document.createElement) {
        "undefined" === typeof opera && (window.opera = !1); marqueeInit.ar =
        []; document.write('<style type="text/css">.marquee{white-space:nowrap;overflow:hidden;visibility:hidden;}#marq_kill_marg_bord{border:none!important;margin:0!important;}</style>'); var l = 0, m = [/^\s*$/, /^\s*/, /\s*$/, /[^\/]+$/], r = { position: "relative", overflow: "hidden" }, p = { style: { margin: "0 auto" }, direction: "left", inc: 2, mouse: "pause" }, q, t = function (a, b) { return b.toUpperCase() }; q = /-(.)/g; String.prototype.encamel = function () { return this.replace(q, t) }; marqueeInit.run = function (a) {
            document.getElementById(a) ? new c(l++,
            document.getElementById(a)) : setTimeout(function () { marqueeInit.run(a) }, 300)
        }; c.prototype.setup = function (a) {
            if (!this.mq.setup) {
                this.mq.setup = this; var b, d = this, c = 1E4; "auto" === this.c.style.height && (this.c.style.height = this.m.offsetHeight + 4 + "px"); this.c.appendChild(this.m.cloneNode(!0)); this.m = [this.m, this.m.nextSibling]; "function" === typeof this.mq.initcontent && this.mq.initcontent.apply(this.mq, [this.m]); "cursor driven" === this.mq.mouse && (this.r = this.mq.neutral || 16, this.sinc = this.mq.inc, this.c.onmousemove =
                function (a) { d.mq.stopped = !1; d.directspeed(a) }, this.mq.moveatleast ? (this.mq.inc = this.mq.moveatleast, this.mq.savedirection ? "reverse" === this.mq.savedirection ? this.c.onmouseout = function (a) { d.contains(a) || (d.mq.inc = d.mq.moveatleast, d.mq.direction = "right" === d.mq.direction ? "left" : "right") } : (this.mq.savedirection = this.mq.direction, this.c.onmouseout = function (a) { d.contains(a) || (d.mq.inc = d.mq.moveatleast, d.mq.direction = d.mq.savedirection) }) : this.c.onmouseout = function (a) { d.contains(a) || (d.mq.inc = d.mq.moveatleast) }) :
                this.c.onmouseout = function (a) { d.contains(a) || d.slowdeath() }); this.w = this.m[0].offsetWidth; this.m[0].style.left = this.mq.persist && this.cookie.get(this.mq.uniqueid) ? this.cookie.get(this.mq.uniqueid).split(":")[0] : 0; this.c.id = "marq_kill_marg_bord"; this.m[0].style.top = this.m[1].style.top = Math.floor((this.c.offsetHeight - this.m[0].offsetHeight) / 2 - 0) + "px"; this.c.id = ""; this.c.removeAttribute("id", 0); this.m[1].style.left = this.mq.persist && this.cookie.get(this.mq.uniqueid) ? this.cookie.get(this.mq.uniqueid).split(":")[1] :
                this.w + "px"; for (a = this.mq.moveatleast ? Math.max(this.mq.moveatleast, this.sinc) : this.sinc || this.mq.inc; this.c.offsetWidth > this.w - a && --c;) { b = isNaN(this.cw[0]) ? this.w - a : --this.cw[0]; if (1 > b || this.w < Math.max(1, a)) break; this.c.style.width = isNaN(this.cw[0]) ? this.w - a + "px" : --this.cw[0] + this.cw[1] } this.c.style.visibility = "visible"; this.runit()
            }
        }; c.prototype.slowdeath = function () { var a = this; this.mq.inc && (--this.mq.inc, this.timer = setTimeout(function () { a.slowdeath() }, 100)) }; c.prototype.runit = function () {
            var a = this,
            b = "right" === this.mq.direction ? 1 : -1; this.mq.stopped || this.mq.stopMarquee ? setTimeout(function () { a.runit() }, 300) : ("cursor driven" != this.mq.mouse && (this.mq.inc = Math.max(1, this.mq.inc)), b * parseInt(this.m[0].style.left) >= this.w && (this.m[0].style.left = parseInt(this.m[1].style.left) - b * this.w + "px"), b * parseInt(this.m[1].style.left) >= this.w && (this.m[1].style.left = parseInt(this.m[0].style.left) - b * this.w + "px"), this.m[0].style.left = parseInt(this.m[0].style.left) + b * this.mq.inc + "px", this.m[1].style.left = parseInt(this.m[1].style.left) +
            b * this.mq.inc + "px", window.opera && this.mq.persist && this.cookie.set(this.mq.uniqueid, this.m[0].style.left + ":" + this.m[1].style.left + ":" + this.mq.direction), setTimeout(function () { a.runit() }, 30 + (this.mq.addDelay || 0)))
        }; c.prototype.cookie = {
            set: function (a, b, d) { if (d) { var c = new Date; c.setDate(c.getDate() + d); d = "; expires=" + c.toGMTString() } document.cookie = a + "=" + escape(b) + (d || "") + "; path=/" }, get: function (a) { return (a = document.cookie.match("(^|;) *" + a + "=([^;]*)")) ? unescape(a[2]) : null }, kill: function (a) {
                cook.set(a,
                "", -1)
            }, killall: function () { var a = document.cookie.split(";"), b = a.length - 1; for (b; -1 < b; --b) cook.kill(a[b].split("=")[0]) }
        }; c.prototype.directspeed = function (a) {
            a = a || window.event; this.timer && clearTimeout(this.timer); var b = this.c, d = b.offsetWidth; a = ("number" === typeof a.pageX ? a.pageX : a.clientX + document.body.scrollLeft + document.documentElement.scrollLeft) - b.offsetLeft; for (var c = (d - this.r) / 2, d = (d + this.r) / 2; b = b.offsetParent;) a -= b.offsetLeft; this.mq.direction = a > d ? "left" : "right"; this.mq.inc = Math.round((a > d ? a -
                d : a < c ? c - a : 0) / c * this.sinc)
        }; c.prototype.contains = function (a) { if (a && a.relatedTarget) { a = a.relatedTarget; if (a === this.c) return !0; for (; a = a.parentNode;) if (a === this.c) return !0 } return !1 }; window.addEventListener ? (window.addEventListener("resize", g, !1), window.addEventListener("unload", k, !1)) : window.attachEvent && (window.attachEvent("onresize", g), window.attachEvent("onunload", k))
    }
})();